#!/bin/bash

# Pastikan lolcat terinstall untuk pewarnaan header
if ! command -v lolcat &> /dev/null; then
    apt-get install ruby -y &> /dev/null
    gem install lolcat &> /dev/null
fi

clear

# --- FUNGSI ANIMASI LOADING ---
fun_bar() {
    CMD="$1"
    
    # Menjalankan perintah di background
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        $CMD >/dev/null 2>&1 # Menjalankan fungsi res1 tanpa output ke layar
        touch $HOME/fim      # Membuat file penanda selesai
    ) >/dev/null 2>&1 &

    # Memulai Animasi
    tput civis # Sembunyikan kursor
    echo -ne "  \033[0;33mSedang Memproses Update \033[1;37m- \033[0;33m["
    
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[0;32m#"
            sleep 0.1s
        done
        
        # Cek jika file penanda sudah ada (artinya res1 selesai)
        if [[ -e $HOME/fim ]]; then
            rm $HOME/fim
            break
        fi
        
        # Reset baris jika belum selesai
        echo -e "\033[0;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "  \033[0;33mSedang Memproses Update \033[1;37m- \033[0;33m["
    done
    
    # Tampilan Selesai
    echo -e "\033[0;33m]\033[1;37m -\033[1;32m SUKSES !\033[1;37m"
    tput cnorm # Tampilkan kursor kembali
}

# --- FUNGSI UPDATE UTAMA ---
res1() {
    # 1. Abil Data Dari github Modules
    systemctl stop kyt
    rm -rf /usr/bin/kyt/modules/*
    wget https://github.com/hokagelegend9999/alpha.v2/raw/refs/heads/main/bot/modules.zip
    unzip -o modules.zip > /dev/null 2>&1 
    chmod +x modules/*
    mv modules/* /usr/bin/kyt/modules/
    rm -rf modules
    rm -rf modules.zip
    
    # 1. Abil Data Dari github Modules
    rm -rf /usr/bin/kyt/shell/*
    wget https://github.com/hokagelegend9999/alpha.v2/raw/refs/heads/main/bot/shell.zip
    unzip -o shell.zip > /dev/null 2>&1 
    chmod +x shell/*
    mv modules/* /usr/bin/kyt/shell/
    rm -rf shell
    rm -rf shell.zip

# --- EKSEKUSI ---
systemctl start kyt 
systemctl enable kyt
systemctl restart kyt
rm -rf update-bot
clear
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e " \e[1;97;101m UPDATE BOT TELEGRAM  !             \e[0m"
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e ""
echo -e "  \033[1;91m Update Script Service & Menu\033[1;37m"

# Panggil fungsi animasi dengan argumen fungsi res1
fun_bar 'res1'

echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e ""
echo -e " \033[1;32m Update Selesai! Cek Bot /start.\033[0m"
echo -e ""
read -n 1 -s -r -p "Tekan [ Enter ] untuk kembali ke menu"
menu
